name: Publish to PyPi

on:
 push:
    tags:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - name: Check out this repo
      uses: actions/checkout@v3

    - name: Set Proceed version from repo tag
      run: |
        echo '__version__ = "${{ github.ref_name }}"' > src/proceed/__about__.py

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Hatch
      run: |
        python -m pip install --upgrade pip
        pipx install hatch

    - name: Test with hatch and pytest
      run: |
        hatch run test:cov

    - name: Build and publish to PyPi
      run: |
        hatch build
        hatch publish --user __token__ --auth ${{ secrets.PYPI_TOKEN }}
